### ISSUE TITLE
Use as button vector-icons

### ISSUE THREAD

**Issue by Angelk90** [izzisolomon/react-native-options-menu#2]
Hi @izzisolomon , would it be possible to use the react-native-vector-icons button?

**Comment by izzisolomon** [comment]
Hi,

I just released a new version that allows you to pass in any constant as the button object: 

const myIcon = (<Icon name="rocket" size={30} color="#900" />)
<OptionsMenu
  customButton={myIcon}
  destructiveIndex={1}
  options={["Edit", "Delete", "Cancel"]}
  actions={[this.editPost, this.deletePost]}/>

**Comment by Angelk90** [comment]
Perfect. ;)
Link: https://snack.expo.io/BkUtHQnDQ
