### ISSUE TITLE
Add new features.

### ISSUE THREAD

**Issue by Angelk90** [izzisolomon/react-native-options-menu#3]
Hi @izzisolomon , 
It would be possible to add new features like:
1) Be able to customize the color of the text and the background of the menu, for example a menu with a dark theme.
Link: https://i1.wp.com/www.androidinterview.com/wp-content/uploads/2014/08/android-option-menu3.jpg
2) Give the possibility to each element of the menu to have an icon.
link: https://i.ytimg.com/vi/spSvaWcDPOw/maxresdefault.jpg

**Comment by izzisolomon** [comment]
@Angelk90 The library is using the native android popup menu which doesn't support Icons/different background colors.

**Comment by Angelk90** [comment]
@izzisolomon : But I think there will be a way to do it natively, those are native apps.

**Comment by izzisolomon** [comment]
@Angelk90 there certainly is a way, just not by using the native popup. It can be done by creating a custom view. I may add support for that in the near future.
