### ISSUE TITLE
Disable Options

### ISSUE THREAD

**Issue by naytun** [izzisolomon/react-native-options-menu#4]
How to disable some options depending on some conditions?

**Comment by izzisolomon** [comment]
@naytun you can pass in different options based on conditions something like:

`let optionsA = ["A", "B"];`
`let optionsB = ["C", "D"];`

`<OptionsMenu`
  `customButton={myIcon}`
  `destructiveIndex={1}`
  `options={condition ? optionsA : optionsB}`
  `actions={condition ? actionsA : actionsB}/>`
