### ISSUE TITLE
how do you trigger option menu to show up?

### ISSUE THREAD

**Issue by bishnudev** [izzisolomon/react-native-options-menu#6]
renderOptions = () => {
        const myIcon = (<Icon name="rocket" size={30} color="#900" />)
        return (
            <OptionsMenu
                customButton={myIcon}
                destructiveIndex={1}
                options={["Edit", "Delete"]}
                actions={[ , ]}
            />
        )
    }

i want to trigger this menu when an item is long pressed
onLongPress={() => { this.renderOptions(); }}

but it doesn't show up. why?

**Comment by izzisolomon** [comment]
@bishnudev did you actually pass in an icon? if not it will be invisible

**Comment by lucastonon** [comment]
@izzisolomon 
Suddenly it started giving me this error. Do you have any idea what it is?
<img width="375" alt="Screen Shot 2019-08-03 at 11 51 45" src="https://user-images.githubusercontent.com/38772994/62413414-21293e00-b5e5-11e9-92dd-0b015a503441.png">

**Comment by lucastonon** [comment]
> @izzisolomon
> Suddenly it started giving me this error. Do you have any idea what it is?
> <img alt="Screen Shot 2019-08-03 at 11 51 45" width="375" src="https://user-images.githubusercontent.com/38772994/62413414-21293e00-b5e5-11e9-92dd-0b015a503441.png">

Finally I got it working. I had to manually link binary with libraries on xcode with RCTActionSheetManager
